name: Sync Repo with S3 Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
        
      - name: Sync Repo with S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.adamonaws.com }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIA3AATCJDSPEAT7UPE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.rrS1KHA41UuHWLkBSMZQW1bIJOlGefv1Se9lsTs }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'public'      # optional: defaults to entire repository
  
