# inside .github/workflows/action.yml
name: S3 Upload
on: push

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: S3 Upload
        uses: koraykoska/s3-upload-github-action@0.1.3

      - uses: actions/checkout@master

      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        with:
          path: ./index.html
        env:
          S3_ENDPOINT: 'http://adamonaws.com.s3-website-us-west-1.amazonaws.com/'
          S3_BUCKET: ${{ secrets.adamonaws.com }}
          S3_ACCESS_KEY_ID: ${{ secrets.AKIA3AATCJDSE6WZLNFP }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.aTs8wenGNAcVKaqvCooiXZ8A0VGUxb0FZrSwnrua }}
