# inside .github/workflows/your-action.yml
name: Add File to S3 Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
        
      - name: Upload file to S3 bucket
        uses: zdurham/s3-upload-github-action@1.0.1
        with:
          args: --acl public-read
        env:
          FILE: ./index.html
          AWS_REGION: 'us-west-1'
          S3_BUCKET: ${{ secrets.adamonaws.com }}
          S3_KEY: ${{ secrets.adamonaws-key }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIA3AATCJDSPEAT7UPE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.rrS1KHA41UuHWLkBSMZQW1bIJOlGefv1Se9lsTs/ }}
