name: Upload to S3

on: [push]

jobs:
  upload:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: AdamOnAWS/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AKIA3AATCJDSE6WZLNFP }}
          aws_secret_access_key: ${{ secrets.aTs8wenGNAcVKaqvCooiXZ8A0VGUxb0FZrSwnrua}}
          aws_bucket: ${{ secrets.adamonaws.com }}
          source_dir: 'index.html'
